In [ ]:
import pandas as pd

df = pd.read_csv('application_train.csv')
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [ ]:
print(df.shape)
print()
print(df['TARGET'].describe())
print()
print(df.isna().sum().sum())
print()
print(df.isnull().sum().sort_values(ascending=False))

(307511, 122)

count    307511.000000
mean          0.080729
std           0.272419
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: TARGET, dtype: float64

9152465

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
                             ...
FLAG_DOCUMENT_16                 0
FLAG_DOCUMENT_15                 0
FLAG_DOCUMENT_14                 0
FLAG_DOCUMENT_20                 0
FLAG_DOCUMENT_21                 0
Length: 122, dtype: int64

In [ ]:
df['TARGET'].value_counts()

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [ ]:
import numpy as np
numerical_features = df.select_dtypes(include=[np.number]).columns
categorical_features = df.select_dtypes(include=['object']).columns

In [ ]:
print(numerical_features)

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=106)

In [ ]:
print(categorical_features)

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='object')

In [ ]:
df['AMT_CREDIT'].unique()

array([ 406597.5, 1293502.5,  135000. , ...,  181989. ,  743863.5,
       1391130. ])

In [ ]:
ctr = 0
for feature in numerical_features:
    if (len(df[feature].unique())<10) :
        print(feature)
        print(df[feature].unique())
        ctr+=1
print(ctr)

TARGET
[1 0]
FLAG_MOBIL
[1 0]
FLAG_EMP_PHONE
[1 0]
FLAG_WORK_PHONE
[0 1]
FLAG_CONT_MOBILE
[1 0]
FLAG_PHONE
[1 0]
FLAG_EMAIL
[0 1]
REGION_RATING_CLIENT
[2 1 3]
REGION_RATING_CLIENT_W_CITY
[2 1 3]
REG_REGION_NOT_LIVE_REGION
[0 1]
REG_REGION_NOT_WORK_REGION
[0 1]
LIVE_REGION_NOT_WORK_REGION
[0 1]
REG_CITY_NOT_LIVE_CITY
[0 1]
REG_CITY_NOT_WORK_CITY
[0 1]
LIVE_CITY_NOT_WORK_CITY
[0 1]
FLAG_DOCUMENT_2
[0 1]
FLAG_DOCUMENT_3
[1 0]
FLAG_DOCUMENT_4
[0 1]
FLAG_DOCUMENT_5
[0 1]
FLAG_DOCUMENT_6
[0 1]
FLAG_DOCUMENT_7
[0 1]
FLAG_DOCUMENT_8
[0 1]
FLAG_DOCUMENT_9
[0 1]
FLAG_DOCUMENT_10
[0 1]
FLAG_DOCUMENT_11
[0 1]
FLAG_DOCUMENT_12
[0 1]
FLAG_DOCUMENT_13
[0 1]
FLAG_DOCUMENT_14
[0 1]
FLAG_DOCUMENT_15
[0 1]
FLAG_DOCUMENT_16
[0 1]
FLAG_DOCUMENT_17
[0 1]
FLAG_DOCUMENT_18
[0 1]
FLAG_DOCUMENT_19
[0 1]
FLAG_DOCUMENT_20
[0 1]
FLAG_DOCUMENT_21
[0 1]
AMT_REQ_CREDIT_BUREAU_HOUR
[ 0. nan  1.  2.  3.  4.]
36

In [ ]:
for feature in numerical_features:
    if (len(df[feature].unique())== 2) :
        print(feature)

TARGET
FLAG_MOBIL
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
FLAG_DOCUMENT_2
FLAG_DOCUMENT_3
FLAG_DOCUMENT_4
FLAG_DOCUMENT_5
FLAG_DOCUMENT_6
FLAG_DOCUMENT_7
FLAG_DOCUMENT_8
FLAG_DOCUMENT_9
FLAG_DOCUMENT_10
FLAG_DOCUMENT_11
FLAG_DOCUMENT_12
FLAG_DOCUMENT_13
FLAG_DOCUMENT_14
FLAG_DOCUMENT_15
FLAG_DOCUMENT_16
FLAG_DOCUMENT_17
FLAG_DOCUMENT_18
FLAG_DOCUMENT_19
FLAG_DOCUMENT_20
FLAG_DOCUMENT_21

In [ ]:
doc_cols = [f"FLAG_DOCUMENT_{i}" for i in range(2, 22)]

summary = pd.DataFrame({
    "clients_with_doc": df[doc_cols].sum(),
    "percentage": df[doc_cols].mean() * 100
}).sort_values("percentage", ascending=False)

print(summary)

                  clients_with_doc  percentage
FLAG_DOCUMENT_3             218340   71.002338
FLAG_DOCUMENT_6              27078    8.805539
FLAG_DOCUMENT_8              25024    8.137595
FLAG_DOCUMENT_5               4648    1.511491
FLAG_DOCUMENT_16              3053    0.992810
FLAG_DOCUMENT_18              2500    0.812979
FLAG_DOCUMENT_11              1203    0.391206
FLAG_DOCUMENT_9               1198    0.389580
FLAG_DOCUMENT_13              1084    0.352508
FLAG_DOCUMENT_14               903    0.293648
FLAG_DOCUMENT_15               372    0.120971
FLAG_DOCUMENT_19               183    0.059510
FLAG_DOCUMENT_20               156    0.050730
FLAG_DOCUMENT_21               103    0.033495
FLAG_DOCUMENT_17                82    0.026666
FLAG_DOCUMENT_7                 59    0.019186
FLAG_DOCUMENT_4                 25    0.008130
FLAG_DOCUMENT_2                 13    0.004227
FLAG_DOCUMENT_10                 7    0.002276
FLAG_DOCUMENT_12                 2    0.000650

In [ ]:
df.groupby('FLAG_DOCUMENT_3')['TARGET'].mean()

FLAG_DOCUMENT_3
0    0.061825
1    0.088449
Name: TARGET, dtype: float64

In [ ]:
results = {}

for col in doc_cols:
    results[col] = df.groupby(col)['TARGET'].mean()

pd.DataFrame(results).T

                         0         1
FLAG_DOCUMENT_2   0.080719  0.307692
FLAG_DOCUMENT_3   0.061825  0.088449
FLAG_DOCUMENT_4   0.080735  0.000000
FLAG_DOCUMENT_5   0.080739  0.080034
FLAG_DOCUMENT_6   0.083150  0.055654
FLAG_DOCUMENT_7   0.080735  0.050847
FLAG_DOCUMENT_8   0.081381  0.073370
FLAG_DOCUMENT_9   0.080803  0.061770
FLAG_DOCUMENT_10  0.080731  0.000000
FLAG_DOCUMENT_11  0.080801  0.062344
FLAG_DOCUMENT_12  0.080729  0.000000
FLAG_DOCUMENT_13  0.080916  0.027675
FLAG_DOCUMENT_14  0.080869  0.033223
FLAG_DOCUMENT_15  0.080791  0.029570
FLAG_DOCUMENT_16  0.081046  0.049132
FLAG_DOCUMENT_17  0.080744  0.024390
FLAG_DOCUMENT_18  0.080925  0.056800
FLAG_DOCUMENT_19  0.080738  0.065574
FLAG_DOCUMENT_20  0.080727  0.083333
FLAG_DOCUMENT_21  0.080710  0.135922

In [ ]:
df["DOCS_PROVIDED_COUNT"] = df[doc_cols].sum(axis=1)

In [ ]:
x = [3,16,18,15,14,13,6,8]
doc_cols_needed = [f"FLAG_DOCUMENT_{i}" for i in x]
df["SIGNAL_DOCS_COUNT"] = df[doc_cols_needed].sum(axis=1)

In [ ]:
df[["SIGNAL_DOCS_COUNT","DOCS_PROVIDED_COUNT"]]

        SIGNAL_DOCS_COUNT  DOCS_PROVIDED_COUNT
0                       1                    1
1                       1                    1
2                       0                    0
3                       1                    1
4                       1                    1
...                   ...                  ...
307506                  1                    1
307507                  1                    1
307508                  1                    1
307509                  1                    1
307510                  1                    1

[307511 rows x 2 columns]

In [ ]:
df[df["DOCS_PROVIDED_COUNT"] >2]["DOCS_PROVIDED_COUNT"]

1402      3
1999      3
4027      3
7826      3
9525      3
         ..
297620    3
300259    3
301407    3
304282    3
305288    3
Name: DOCS_PROVIDED_COUNT, Length: 164, dtype: int64

In [ ]:
print(df["SIGNAL_DOCS_COUNT"].describe())

print(df["DOCS_PROVIDED_COUNT"].describe())

count    307511.000000
mean          0.905184
std           0.367081
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
Name: SIGNAL_DOCS_COUNT, dtype: float64
count    307511.000000
mean          0.930155
std           0.344295
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: DOCS_PROVIDED_COUNT, dtype: float64

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head(1)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,DOCS_PROVIDED_COUNT,SIGNAL_DOCS_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.0,0.069,0.0833,0.125,0.0369,0.0202,0.019,0.0,0.0,0.0252,0.0383,0.9722,0.6341,0.0144,0.0,0.069,0.0833,0.125,0.0377,0.022,0.0198,0.0,0.0,0.025,0.0369,0.9722,0.6243,0.0144,0.0,0.069,0.0833,0.125,0.0375,0.0205,0.0193,0.0,0.0,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1,1

In [ ]:
numerical_features_set = set(numerical_features)
def helper(df: pd.DataFrame, cols: list):
    rows = []

    for col in cols:
        missing_pct = df[col].isna().mean()


        rates = df.groupby(df[col].isna())['TARGET'].mean()
        default_present = rates.get(False, np.nan)
        default_missing = rates.get(True, np.nan)


        if col in numerical_features_set:
            corr_target = df[col].corr(df['TARGET'])
            n_unique = np.nan
        else:
            corr_target = np.nan
            n_unique = df[col].nunique()

        rows.append({
            'column': col,
            'missing_pct': missing_pct,
            'default_rate_present': default_present,
            'default_rate_missing': default_missing,
            'corr_with_target': corr_target,
            'n_unique': n_unique
        })

    return pd.DataFrame(rows)

In [ ]:
cols_delete = []

for col in doc_cols:
    if col not in doc_cols_needed :
        cols_delete.append(col)
print(cols_delete)

['FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21']

In [ ]:
df = df.drop(cols_delete,axis=1)

In [ ]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_18,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,DOCS_PROVIDED_COUNT,SIGNAL_DOCS_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0000,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.032561,-9327,-236,-8456.0,-1982,NaN,1,1,0,1,0,0,Sales staff,1.0,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.145570,0.681632,NaN,0.2021,0.0887,0.9876,0.8300,0.0202,0.22,0.1034,0.6042,0.2708,0.0594,0.1484,0.1965,0.0753,0.1095,0.1008,0.0172,0.9782,0.7125,0.0172,0.0806,0.0345,0.4583,0.0417,0.0094,0.0882,0.0853,0.0,0.0125,0.2040,0.0887,0.9876,0.8323,0.0203,0.22,0.1034,0.6042,0.2708,0.0605,0.1509,0.2001,0.0757,0.1118,reg oper account,block of flats,0.2898,"Stone, brick",No,0.0,0.0,0.0,0.0,-273.0,0,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.025164,-20775,365243,-4388.0,-4090,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.115992,NaN,0.0247,0.0435,0.9727,0.6260,0.0022,0.00,0.1034,0.0833,0.1250,0.0579,0.0202,0.0257,0.0000,0.0000,0.0252,0.0451,0.9727,0.6406,0.0022,0.0000,0.1034,0.0833,0.1250,0.0592,0.0220,0.0267,0.0,0.0000,0.0250,0.0435,0.9727,0.6310,0.0022,0.00,0.1034,0.0833,0.1250,0.0589,0.0205,0.0261,0.0000,0.0000,reg oper account,block of flats,0.0214,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0000,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0000,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0000,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,1,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,1,1
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.005313,-11961,-4786,-2562.0,-931,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.514163,0.661024,0.0124,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0061,NaN,NaN,0.0126,NaN,0.9772,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0063,NaN,NaN,0.0125,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0062,NaN,NaN,NaN,block of flats,0.0086,"Stone, brick",No,0.0,0.0,0.0,0.0,-322.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0000,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,1,1

In [ ]:
pd.set_option('display.max_rows', 130)

In [ ]:
cols_to_exclude = {"SK_ID_CURR", "TARGET"}
feature_cols = [col for col in df.columns if col not in cols_to_exclude]

corr_with_target = helper(df, feature_cols)
corr_with_target.sort_values("corr_with_target", ascending=False)

,column,missing_pct,default_rate_present,default_rate_missing,corr_with_target,n_unique
15,DAYS_BIRTH,0.000000,0.080729,NaN,0.078239,NaN
29,REGION_RATING_CLIENT_W_CITY,0.000000,0.080729,NaN,0.060893,NaN
28,REGION_RATING_CLIENT,0.000000,0.080729,NaN,0.058899,NaN
93,DAYS_LAST_PHONE_CHANGE,0.000003,0.080729,0.000000,0.055218,NaN
18,DAYS_ID_PUBLISH,0.000000,0.080729,NaN,0.051457,NaN
36,REG_CITY_NOT_WORK_CITY,0.000000,0.080729,NaN,0.050994,NaN
21,FLAG_EMP_PHONE,0.000000,0.080729,NaN,0.045982,NaN
35,REG_CITY_NOT_LIVE_CITY,0.000000,0.080729,NaN,0.044395,NaN
94,FLAG_DOCUMENT_3,0.000000,0.080729,NaN,0.044346,NaN
17,DAYS_REGISTRATION,0.000000,0.080729,NaN,0.041975,NaN
19,OWN_CAR_AGE,0.659908,0.072441,0.085000,0.037612,NaN
37,LIVE_CITY_NOT_WORK_CITY,0.000000,0.080729,NaN,0.032518,NaN
90,DEF_30_CNT_SOCIAL_CIRCLE,0.003320,0.080880,0.035260,0.032248,NaN
92,DEF_60_CNT_SOCIAL_CIRCLE,0.003320,0.080880,0.035260,0.031276,NaN
22,FLAG_WORK_PHONE,0.000000,0.080729,NaN,0.028524,NaN
107,AMT_REQ_CREDIT_BUREAU_YEAR,0.135016,0.077194,0.103374,0.019930,NaN
4,CNT_CHILDREN,0.000000,0.080729,NaN,0.019187,NaN
27,CNT_FAM_MEMBERS,0.000007,0.080729,0.000000,0.009308,NaN
89,OBS_30_CNT_SOCIAL_CIRCLE,0.003320,0.080880,0.035260,0.009131,NaN
91,OBS_60_CNT_SOCIAL_CIRCLE,0.003320,0.080880,0.035260,0.009022,NaN
33,REG_REGION_NOT_WORK_REGION,0.000000,0.080729,NaN,0.006942,NaN
32,REG_REGION_NOT_LIVE_REGION,0.000000,0.080729,NaN,0.005576,NaN
34,LIVE_REGION_NOT_WORK_REGION,0.000000,0.080729,NaN,0.002819,NaN
103,AMT_REQ_CREDIT_BUREAU_DAY,0.135016,0.077194,0.103374,0.002704,NaN
102,AMT_REQ_CREDIT_BUREAU_HOUR,0.135016,0.077194,0.103374,0.000930,NaN
104,AMT_REQ_CREDIT_BUREAU_WEEK,0.135016,0.077194,0.103374,0.000788,NaN
20,FLAG_MOBIL,0.000000,0.080729,NaN,0.000534,NaN
23,FLAG_CONT_MOBILE,0.000000,0.080729,NaN,0.000370,NaN
68,NONLIVINGAPARTMENTS_MODE,0.694330,0.069130,0.085835,-0.001557,NaN
25,FLAG_EMAIL,0.000000,0.080729,NaN,-0.001758,NaN
106,AMT_REQ_CREDIT_BUREAU_QRT,0.135016,0.077194,0.103374,-0.002022,NaN
82,NONLIVINGAPARTMENTS_MEDI,0.694330,0.069130,0.085835,-0.002757,NaN
54,NONLIVINGAPARTMENTS_AVG,0.694330,0.069130,0.085835,-0.003176,NaN
5,AMT_INCOME_TOTAL,0.000000,0.080729,NaN,-0.003982,NaN
99,FLAG_DOCUMENT_15,0.000000,0.080729,NaN,-0.006536,NaN
101,FLAG_DOCUMENT_18,0.000000,0.080729,NaN,-0.007952,NaN
96,FLAG_DOCUMENT_8,0.000000,0.080729,NaN,-0.008040,NaN
58,YEARS_BEGINEXPLUATATION_MODE,0.487810,0.069947,0.092049,-0.009036,NaN
98,FLAG_DOCUMENT_14,0.000000,0.080729,NaN,-0.009464,NaN
44,YEARS_BEGINEXPLUATATION_AVG,0.487810,0.069947,0.092049,-0.009728,NaN
72,YEARS_BEGINEXPLUATATION_MEDI,0.487810,0.069947,0.092049,-0.009993,NaN
65,LANDAREA_MODE,0.593767,0.069812,0.088198,-0.010174,NaN
51,LANDAREA_AVG,0.593767,0.069812,0.088198,-0.010885,NaN
79,LANDAREA_MEDI,0.593767,0.069812,0.088198,-0.011256,NaN
97,FLAG_DOCUMENT_13,0.000000,0.080729,NaN,-0.011583,NaN
100,FLAG_DOCUMENT_16,0.000000,0.080729,NaN,-0.011615,NaN
105,AMT_REQ_CREDIT_BUREAU_MON,0.135016,0.077194,0.103374,-0.012462,NaN
69,NONLIVINGAREA_MODE,0.551792,0.068890,0.090345,-0.012711,NaN
7,AMT_ANNUITY,0.000039,0.080732,0.000000,-0.012817,NaN
83,NONLIVINGAREA_MEDI,0.551792,0.068890,0.090345,-0.013337,NaN
55,NONLIVINGAREA_AVG,0.551792,0.068890,0.090345,-0.013578,NaN
60,COMMONAREA_MODE,0.698723,0.069102,0.085742,-0.016340,NaN
62,ENTRANCES_MODE,0.503488,0.069517,0.091786,-0.017387,NaN
46,COMMONAREA_AVG,0.698723,0.069102,0.085742,-0.018550,NaN
74,COMMONAREA_MEDI,0.698723,0.069102,0.085742,-0.018573,NaN
76,ENTRANCES_MEDI,0.503488,0.069517,0.091786,-0.019025,NaN
48,ENTRANCES_AVG,0.503488,0.069517,0.091786,-0.019172,NaN
57,BASEMENTAREA_MODE,0.585160,0.068881,0.089128,-0.019952,NaN
59,YEARS_BUILD_MODE,0.664978,0.068664,0.086807,-0.022068,NaN
71,BASEMENTAREA_MEDI,0.585160,0.068881,0.089128,-0.022081,NaN
45,YEARS_BUILD_AVG,0.664978,0.068664,0.086807,-0.022149,NaN
73,YEARS_BUILD_MEDI,0.664978,0.068664,0.086807,-0.022326,NaN
43,BASEMENTAREA_AVG,0.585160,0.068881,0.089128,-0.022746,NaN
66,LIVINGAPARTMENTS_MODE,0.683550,0.068882,0.086214,-0.023393,NaN
24,FLAG_PHONE,0.000000,0.080729,NaN,-0.023806,NaN
31,HOUR_APPR_PROCESS_START,0.000000,0.080729,NaN,-0.024166,NaN
80,LIVINGAPARTMENTS_MEDI,0.683550,0.068882,0.086214,-0.024621,NaN
52,LIVINGAPARTMENTS_AVG,0.683550,0.068882,0.086214,-0.025031,NaN
56,APARTMENTS_MODE,0.507497,0.069594,0.091535,-0.027284,NaN
95,FLAG_DOCUMENT_6,0.000000,0.080729,NaN,-0.028602,NaN
70,APARTMENTS_MEDI,0.507497,0.069594,0.091535,-0.029184,NaN
42,APARTMENTS_AVG,0.507497,0.069594,0.091535,-0.029498,NaN
6,AMT_CREDIT,0.000000,0.080729,NaN,-0.030369,NaN
67,LIVINGAREA_MODE,0.501933,0.069953,0.091422,-0.030685,NaN
61,ELEVATORS_MODE,0.532960,0.069002,0.091006,-0.032131,NaN
86,TOTALAREA_MODE,0.482685,0.069896,0.092339,-0.032596,NaN
64,FLOORSMIN_MODE,0.678486,0.068950,0.086311,-0.032698,NaN
81,LIVINGAREA_MEDI,0.501933,0.069953,0.091422,-0.032739,NaN
53,LIVINGAREA_AVG,0.501933,0.069953,0.091422,-0.032997,NaN
78,FLOORSMIN_MEDI,0.678486,0.068950,0.086311,-0.033394,NaN
50,FLOORSMIN_AVG,0.678486,0.068950,0.086311,-0.033614,NaN
75,ELEVATORS_MEDI,0.532960,0.069002,0.091006,-0.033863,NaN
47,ELEVATORS_AVG,0.532960,0.069002,0.091006,-0.034199,NaN
14,REGION_POPULATION_RELATIVE,0.000000,0.080729,NaN,-0.037227,NaN
8,AMT_GOODS_PRICE,0.000904,0.080734,0.075540,-0.039645,NaN
63,FLOORSMAX_MODE,0.497608,0.069655,0.091910,-0.043226,NaN
77,FLOORSMAX_MEDI,0.497608,0.069655,0.091910,-0.043768,NaN
49,FLOORSMAX_AVG,0.497608,0.069655,0.091910,-0.044003,NaN
16,DAYS_EMPLOYED,0.000000,0.080729,NaN,-0.044932,NaN
39,EXT_SOURCE_1,0.563811,0.074955,0.085195,-0.155317,NaN
40,EXT_SOURCE_2,0.002146,0.080733,0.078788,-0.160472,NaN
41,EXT_SOURCE_3,0.198253,0.077665,0.093119,-0.178919,NaN
0,NAME_CONTRACT_TYPE,0.000000,0.080729,NaN,NaN,2.0
1,CODE_GENDER,0.000000,0.080729,NaN,NaN,3.0
2,FLAG_OWN_CAR,0.000000,0.080729,NaN,NaN,2.0
3,FLAG_OWN_REALTY,0.000000,0.080729,NaN,NaN,2.0
9,NAME_TYPE_SUITE,0.004201,0.080841,0.054180,NaN,7.0
10,NAME_INCOME_TYPE,0.000000,0.080729,NaN,NaN,8.0
11,NAME_EDUCATION_TYPE,0.000000,0.080729,NaN,NaN,5.0
12,NAME_FAMILY_STATUS,0.000000,0.080729,NaN,NaN,6.0
13,NAME_HOUSING_TYPE,0.000000,0.080729,NaN,NaN,6.0
26,OCCUPATION_TYPE,0.313455,0.087851,0.065131,NaN,18.0
30,WEEKDAY_APPR_PROCESS_START,0.000000,0.080729,NaN,NaN,7.0
38,ORGANIZATION_TYPE,0.000000,0.080729,NaN,NaN,58.0
84,FONDKAPREMONT_MODE,0.683862,0.068919,0.086188,NaN,4.0
85,HOUSETYPE_MODE,0.501761,0.069870,0.091512,NaN,3.0
87,WALLSMATERIAL_MODE,0.508408,0.069815,0.091281,NaN,7.0
88,EMERGENCYSTATE_MODE,0.473983,0.070025,0.092607,NaN,2.0
108,DOCS_PROVIDED_COUNT,0.000000,0.080729,NaN,NaN,5.0
109,SIGNAL_DOCS_COUNT,0.000000,0.080729,NaN,NaN,3.0

In [ ]:
df[df["DAYS_BIRTH"]<0]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_18,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,DOCS_PROVIDED_COUNT,SIGNAL_DOCS_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0000,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.032561,-9327,-236,-8456.0,-1982,NaN,1,1,0,1,0,0,Sales staff,1.0,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.145570,0.681632,NaN,0.2021,0.0887,0.9876,0.8300,0.0202,0.22,0.1034,0.6042,0.2708,0.0594,0.1484,0.1965,0.0753,0.1095,0.1008,0.0172,0.9782,0.7125,0.0172,0.0806,0.0345,0.4583,0.0417,0.0094,0.0882,0.0853,0.0,0.0125,0.2040,0.0887,0.9876,0.8323,0.0203,0.22,0.1034,0.6042,0.2708,0.0605,0.1509,0.2001,0.0757,0.1118,reg oper account,block of flats,0.2898,"Stone, brick",No,0.0,0.0,0.0,0.0,-273.0,0,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.025164,-20775,365243,-4388.0,-4090,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.115992,NaN,0.0247,0.0435,0.9727,0.6260,0.0022,0.00,0.1034,0.0833,0.1250,0.0579,0.0202,0.0257,0.0000,0.0000,0.0252,0.0451,0.9727,0.6406,0.0022,0.0000,0.1034,0.0833,0.1250,0.0592,0.0220,0.0267,0.0,0.0000,0.0250,0.0435,0.9727,0.6310,0.0022,0.00,0.1034,0.0833,0.1250,0.0589,0.0205,0.0261,0.0000,0.0000,reg oper account,block of flats,0.0214,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0000,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0000,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0000,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,1,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,1,1
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.005313,-11961,-4786,-2562.0,-931,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.514163,0.661024,0.0124,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0061,NaN,NaN,0.0126,NaN,0.9772,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0063,NaN,NaN,0.0125,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0062,NaN,NaN,NaN,block of flats,0.0086,"Stone, brick",No,0.0,0.0,0.0,0.0,-322.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0000,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,1,1

In [ ]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_18,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,DOCS_PROVIDED_COUNT,SIGNAL_DOCS_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0000,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.032561,-9327,-236,-8456.0,-1982,NaN,1,1,0,1,0,0,Sales staff,1.0,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.145570,0.681632,NaN,0.2021,0.0887,0.9876,0.8300,0.0202,0.22,0.1034,0.6042,0.2708,0.0594,0.1484,0.1965,0.0753,0.1095,0.1008,0.0172,0.9782,0.7125,0.0172,0.0806,0.0345,0.4583,0.0417,0.0094,0.0882,0.0853,0.0,0.0125,0.2040,0.0887,0.9876,0.8323,0.0203,0.22,0.1034,0.6042,0.2708,0.0605,0.1509,0.2001,0.0757,0.1118,reg oper account,block of flats,0.2898,"Stone, brick",No,0.0,0.0,0.0,0.0,-273.0,0,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.025164,-20775,365243,-4388.0,-4090,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.115992,NaN,0.0247,0.0435,0.9727,0.6260,0.0022,0.00,0.1034,0.0833,0.1250,0.0579,0.0202,0.0257,0.0000,0.0000,0.0252,0.0451,0.9727,0.6406,0.0022,0.0000,0.1034,0.0833,0.1250,0.0592,0.0220,0.0267,0.0,0.0000,0.0250,0.0435,0.9727,0.6310,0.0022,0.00,0.1034,0.0833,0.1250,0.0589,0.0205,0.0261,0.0000,0.0000,reg oper account,block of flats,0.0214,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0000,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0000,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0000,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,1,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,1,1
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.005313,-11961,-4786,-2562.0,-931,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.514163,0.661024,0.0124,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0061,NaN,NaN,0.0126,NaN,0.9772,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0063,NaN,NaN,0.0125,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0062,NaN,NaN,NaN,block of flats,0.0086,"Stone, brick",No,0.0,0.0,0.0,0.0,-322.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0000,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,1,1

In [ ]:
ext_cols = ["EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]

ext_features = pd.DataFrame({
    "EXT_SOURCE_MEAN": df[ext_cols].mean(axis=1),
    "EXT_SOURCE_STD": df[ext_cols].std(axis=1),
    "EXT_SOURCE_RANGE": df[ext_cols].max(axis=1) - df[ext_cols].min(axis=1),
    "EXT_SOURCE_COUNT": df[ext_cols].notna().sum(axis=1)
})

ext_features.head()

   EXT_SOURCE_MEAN  EXT_SOURCE_STD  EXT_SOURCE_RANGE  EXT_SOURCE_COUNT
0         0.161787        0.092026          0.179912                 3
1         0.466757        0.219895          0.310978                 2
2         0.642739        0.122792          0.173655                 2
3         0.650442             NaN          0.000000                 1
4         0.322738             NaN          0.000000                 1

In [ ]:
ext_cols = ["EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]

df["EXT_SOURCE_MEAN"] = df[ext_cols].mean(axis=1)
df["EXT_SOURCE_STD"] = df[ext_cols].std(axis=1)
df["EXT_SOURCE_RANGE"] = df[ext_cols].max(axis=1) - df[ext_cols].min(axis=1)
df["EXT_SOURCE_COUNT"] = df[ext_cols].notna().sum(axis=1)

In [ ]:
df[ext_cols].describe()

        EXT_SOURCE_1  EXT_SOURCE_2   EXT_SOURCE_3
count  134133.000000  3.068510e+05  246546.000000
mean        0.502130  5.143927e-01       0.510853
std         0.211062  1.910602e-01       0.194844
min         0.014568  8.173617e-08       0.000527
25%         0.334007  3.924574e-01       0.370650
50%         0.505998  5.659614e-01       0.535276
75%         0.675053  6.636171e-01       0.669057
max         0.962693  8.549997e-01       0.896010

In [ ]:
tmp=["EXT_SOURCE_MEAN","EXT_SOURCE_STD","EXT_SOURCE_RANGE","EXT_SOURCE_COUNT"]

In [ ]:
df[tmp].describe()

       EXT_SOURCE_MEAN  EXT_SOURCE_STD  EXT_SOURCE_RANGE  EXT_SOURCE_COUNT
count    307339.000000    2.706020e+05     307339.000000     307511.000000
mean          0.509251    1.512456e-01          0.216300          2.235790
std           0.149802    9.991074e-02          0.172253          0.649986
min           0.000006    3.538459e-07          0.000000          0.000000
25%           0.413648    7.238552e-02          0.069460          2.000000
50%           0.524502    1.360209e-01          0.190871          2.000000
75%           0.622819    2.143878e-01          0.335072          3.000000
max           0.878903    6.519439e-01          0.921988          3.000000

In [ ]:
df[df["EXT_SOURCE_COUNT"] == 0]["EXT_SOURCE_COUNT"].count()

np.int64(172)

In [ ]:
print(df['DAYS_EMPLOYED'].describe())
print(df['DAYS_EMPLOYED'].value_counts().head(10))

count    307511.000000
mean      63815.045904
std      141275.766519
min      -17912.000000
25%       -2760.000000
50%       -1213.000000
75%        -289.000000
max      365243.000000
Name: DAYS_EMPLOYED, dtype: float64
DAYS_EMPLOYED
 365243    55374
-200         156
-224         152
-230         151
-199         151
-212         150
-384         143
-229         143
-231         140
-207         138
Name: count, dtype: int64

In [ ]:
df['DAYS_EMPLOYED_ANOMALY'] = (df['DAYS_EMPLOYED'] == 365243).astype(int)

df.loc[df["DAYS_EMPLOYED"] == 365243, "DAYS_EMPLOYED"] = np.nan

In [ ]:
df.groupby('DAYS_EMPLOYED_ANOMALY')['TARGET'].mean()

DAYS_EMPLOYED_ANOMALY
0    0.086600
1    0.053996
Name: TARGET, dtype: float64

In [ ]:
print(df["DAYS_BIRTH"].value_counts().head())
print(df["DAYS_REGISTRATION"].value_counts().head())
print(df["DAYS_ID_PUBLISH"].value_counts().head())
print(df["DAYS_LAST_PHONE_CHANGE"].value_counts().head())

DAYS_BIRTH
-13749    43
-13481    42
-10020    41
-18248    41
-15771    40
Name: count, dtype: int64
DAYS_REGISTRATION
-1.0    113
-7.0     98
-6.0     96
-4.0     92
-2.0     92
Name: count, dtype: int64
DAYS_ID_PUBLISH
-4053    169
-4095    162
-4046    161
-4417    159
-4256    158
Name: count, dtype: int64
DAYS_LAST_PHONE_CHANGE
 0.0    37672
-1.0     2812
-2.0     2318
-3.0     1763
-4.0     1285
Name: count, dtype: int64

In [ ]:
df[["DAYS_BIRTH","DAYS_REGISTRATION","DAYS_ID_PUBLISH","DAYS_LAST_PHONE_CHANGE"]].describe()

,DAYS_BIRTH,DAYS_REGISTRATION,DAYS_ID_PUBLISH,DAYS_LAST_PHONE_CHANGE
count,307511.000000,307511.000000,307511.000000,307510.000000
mean,-16036.995067,-4986.120328,-2994.202373,-962.858788
std,4363.988632,3522.886321,1509.450419,826.808487
min,-25229.000000,-24672.000000,-7197.000000,-4292.000000
25%,-19682.000000,-7479.500000,-4299.000000,-1570.000000
50%,-15750.000000,-4504.000000,-3254.000000,-757.000000
75%,-12413.000000,-2010.000000,-1720.000000,-274.000000
max,-7489.000000,0.000000,0.000000,0.000000

In [ ]:
df.groupby(df['DAYS_LAST_PHONE_CHANGE'] == 0)['TARGET'].mean()

DAYS_LAST_PHONE_CHANGE
False    0.078506
True     0.096650
Name: TARGET, dtype: float64

In [ ]:
df['PHONE_CHANGE_AT_APPLICATION'] = (df['DAYS_LAST_PHONE_CHANGE'] == 0).astype(int)

In [ ]:
df_b.groupby("SK_ID_CURR").count()

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
SK_ID_CURR,,,,,,,,,,,,,,,,
100001,7,7,7,7,7,7,4,0,7,7,7,6,7,7,7,7
100002,8,8,8,8,8,6,6,5,8,8,5,4,8,8,8,7
100003,4,4,4,4,4,4,3,4,4,4,4,4,4,4,4,0
100004,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,0
100005,3,3,3,3,3,3,1,1,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456249,13,13,13,13,13,12,12,5,13,13,10,7,13,13,13,0
456250,3,3,3,3,3,3,1,2,3,3,3,3,3,3,3,3
456253,4,4,4,4,4,4,2,0,4,4,4,4,4,4,4,3
456254,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1
456255,11,11,11,11,11,11,6,5,11,11,8,5,11,11,11,9

In [ ]:
df_b.head(5)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [ ]:
print(df_b.shape)
print(df_b.dtypes)

(1716428, 17)
SK_ID_CURR                  int64
SK_ID_BUREAU                int64
CREDIT_ACTIVE              object
CREDIT_CURRENCY            object
DAYS_CREDIT                 int64
CREDIT_DAY_OVERDUE          int64
DAYS_CREDIT_ENDDATE       float64
DAYS_ENDDATE_FACT         float64
AMT_CREDIT_MAX_OVERDUE    float64
CNT_CREDIT_PROLONG          int64
AMT_CREDIT_SUM            float64
AMT_CREDIT_SUM_DEBT       float64
AMT_CREDIT_SUM_LIMIT      float64
AMT_CREDIT_SUM_OVERDUE    float64
CREDIT_TYPE                object
DAYS_CREDIT_UPDATE          int64
AMT_ANNUITY               float64
dtype: object

In [ ]:
df_b['CREDIT_ACTIVE'].unique()

array(['Closed', 'Active', 'Sold', 'Bad debt'], dtype=object)

In [ ]:
df_b['CREDIT_TYPE'].unique()

array(['Consumer credit', 'Credit card', 'Mortgage', 'Car loan',
       'Microloan', 'Loan for working capital replenishment',
       'Loan for business development', 'Real estate loan',
       'Unknown type of loan', 'Another type of loan',
       'Cash loan (non-earmarked)', 'Loan for the purchase of equipment',
       'Mobile operator loan', 'Interbank credit',
       'Loan for purchase of shares (margin lending)'], dtype=object)

In [ ]:
bureau_active = pd.get_dummies(df_b["CREDIT_ACTIVE"], prefix="CREDIT_ACTIVE")
df_b = pd.concat([df_b, bureau_active], axis=1)

bureau_type = pd.get_dummies(df_b["CREDIT_TYPE"], prefix="CREDIT_TYPE")
df_b = pd.concat([df_b, bureau_type], axis=1)

In [ ]:
df_b.shape

(1716428, 36)

In [ ]:
df_b = df_b.drop(["CREDIT_ACTIVE","CREDIT_TYPE"],axis=1)

In [ ]:
df_b.shape

(1716428, 34)

In [ ]:
df_b.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_CURRENCY', 'DAYS_CREDIT',
       'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT',
       'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM',
       'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE',
       'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY', 'CREDIT_ACTIVE_Active',
       'CREDIT_ACTIVE_Bad debt', 'CREDIT_ACTIVE_Closed', 'CREDIT_ACTIVE_Sold',
       'CREDIT_TYPE_Another type of loan', 'CREDIT_TYPE_Car loan',
       'CREDIT_TYPE_Cash loan (non-earmarked)', 'CREDIT_TYPE_Consumer credit',
       'CREDIT_TYPE_Credit card', 'CREDIT_TYPE_Interbank credit',
       'CREDIT_TYPE_Loan for business development',
       'CREDIT_TYPE_Loan for purchase of shares (margin lending)',
       'CREDIT_TYPE_Loan for the purchase of equipment',
       'CREDIT_TYPE_Loan for working capital replenishment',
       'CREDIT_TYPE_Microloan', 'CREDIT_TYPE_Mobile operator loan',
       'CREDIT_TYPE_Mortgage', 'CREDIT_TYPE_Real estate loan',
       'CREDIT_TYPE_Unknown type of loan'],
      dtype='object')

In [ ]:
aggregations = {


    "SK_ID_BUREAU": ["count"],


    "DAYS_CREDIT": ["min", "max", "mean"],
    "DAYS_CREDIT_ENDDATE": ["min", "max", "mean"],
    "DAYS_ENDDATE_FACT": ["min", "max", "mean"],
    "DAYS_CREDIT_UPDATE": ["min", "max", "mean"],


    "CREDIT_DAY_OVERDUE": ["max", "mean"],
    "AMT_CREDIT_MAX_OVERDUE": ["max", "mean"],
    "AMT_CREDIT_SUM_OVERDUE": ["sum", "max"],


    "AMT_CREDIT_SUM": ["sum", "mean", "max"],
    "AMT_CREDIT_SUM_DEBT": ["sum", "mean", "max"],
    "AMT_CREDIT_SUM_LIMIT": ["sum", "mean", "max"],


    "AMT_ANNUITY": ["sum", "mean", "max"],


    "CNT_CREDIT_PROLONG": ["sum", "max"],


    "CREDIT_ACTIVE_Active": ["sum"],
    "CREDIT_ACTIVE_Bad debt": ["sum"],
    "CREDIT_ACTIVE_Closed": ["sum"],
    "CREDIT_ACTIVE_Sold": ["sum"],

    "CREDIT_TYPE_Another type of loan": ["sum"],
    "CREDIT_TYPE_Car loan": ["sum"],
    "CREDIT_TYPE_Cash loan (non-earmarked)": ["sum"],
    "CREDIT_TYPE_Consumer credit": ["sum"],
    "CREDIT_TYPE_Credit card": ["sum"],
    "CREDIT_TYPE_Interbank credit": ["sum"],
    "CREDIT_TYPE_Loan for business development": ["sum"],
    "CREDIT_TYPE_Loan for purchase of shares (margin lending)": ["sum"],
    "CREDIT_TYPE_Loan for the purchase of equipment": ["sum"],
    "CREDIT_TYPE_Loan for working capital replenishment": ["sum"],
    "CREDIT_TYPE_Microloan": ["sum"],
    "CREDIT_TYPE_Mobile operator loan": ["sum"],
    "CREDIT_TYPE_Mortgage": ["sum"],
    "CREDIT_TYPE_Real estate loan": ["sum"],
    "CREDIT_TYPE_Unknown type of loan": ["sum"]
}

bureau_agg = df_b.groupby("SK_ID_CURR").agg(aggregations)

bureau_agg.columns = [
    f"{col}_{agg}" for col, agg in bureau_agg.columns
]

In [ ]:
print(bureau_agg.shape )
bureau_agg.head()

(305811, 52)

,SK_ID_BUREAU_count,DAYS_CREDIT_min,DAYS_CREDIT_max,DAYS_CREDIT_mean,DAYS_CREDIT_ENDDATE_min,DAYS_CREDIT_ENDDATE_max,DAYS_CREDIT_ENDDATE_mean,DAYS_ENDDATE_FACT_min,DAYS_ENDDATE_FACT_max,DAYS_ENDDATE_FACT_mean,DAYS_CREDIT_UPDATE_min,DAYS_CREDIT_UPDATE_max,DAYS_CREDIT_UPDATE_mean,CREDIT_DAY_OVERDUE_max,CREDIT_DAY_OVERDUE_mean,AMT_CREDIT_MAX_OVERDUE_max,AMT_CREDIT_MAX_OVERDUE_mean,AMT_CREDIT_SUM_OVERDUE_sum,AMT_CREDIT_SUM_OVERDUE_max,AMT_CREDIT_SUM_sum,AMT_CREDIT_SUM_mean,AMT_CREDIT_SUM_max,AMT_CREDIT_SUM_DEBT_sum,AMT_CREDIT_SUM_DEBT_mean,AMT_CREDIT_SUM_DEBT_max,AMT_CREDIT_SUM_LIMIT_sum,AMT_CREDIT_SUM_LIMIT_mean,AMT_CREDIT_SUM_LIMIT_max,AMT_ANNUITY_sum,AMT_ANNUITY_mean,AMT_ANNUITY_max,CNT_CREDIT_PROLONG_sum,CNT_CREDIT_PROLONG_max,CREDIT_ACTIVE_Active_sum,CREDIT_ACTIVE_Bad debt_sum,CREDIT_ACTIVE_Closed_sum,CREDIT_ACTIVE_Sold_sum,CREDIT_TYPE_Another type of loan_sum,CREDIT_TYPE_Car loan_sum,CREDIT_TYPE_Cash loan (non-earmarked)_sum,CREDIT_TYPE_Consumer credit_sum,CREDIT_TYPE_Credit card_sum,CREDIT_TYPE_Interbank credit_sum,CREDIT_TYPE_Loan for business development_sum,CREDIT_TYPE_Loan for purchase of shares (margin lending)_sum,CREDIT_TYPE_Loan for the purchase of equipment_sum,CREDIT_TYPE_Loan for working capital replenishment_sum,CREDIT_TYPE_Microloan_sum,CREDIT_TYPE_Mobile operator loan_sum,CREDIT_TYPE_Mortgage_sum,CREDIT_TYPE_Real estate loan_sum,CREDIT_TYPE_Unknown type of loan_sum
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,7,-1572,-49,-735.000000,-1329.0,1778.0,82.428571,-1328.0,-544.0,-825.500000,-155,-6,-93.142857,0,0.0,NaN,NaN,0.0,0.0,1453365.000,207623.571429,378000.0,596686.5,85240.928571,373239.0,0.000,0.00000,0.000,24817.5,3545.357143,10822.5,0,0,3,0,4,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0
100002,8,-1437,-103,-874.000000,-1072.0,780.0,-349.000000,-1185.0,-36.0,-697.500000,-1185,-7,-499.875000,0,0.0,5043.645,1681.029,0.0,0.0,865055.565,108131.945625,450000.0,245781.0,49156.200000,245781.0,31988.565,7997.14125,31988.565,0.0,0.000000,0.0,0,0,2,0,6,0,0,0,0,4,4,0,0,0,0,0,0,0,0,0,0
100003,4,-2586,-606,-1400.750000,-2434.0,1216.0,-544.500000,-2131.0,-540.0,-1097.333333,-2131,-43,-816.000000,0,0.0,0.000,0.000,0.0,0.0,1017400.500,254350.125000,810000.0,0.0,0.000000,0.0,810000.000,202500.00000,810000.000,0.0,NaN,NaN,0,0,1,0,3,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0
100004,2,-1326,-408,-867.000000,-595.0,-382.0,-488.500000,-683.0,-382.0,-532.500000,-682,-382,-532.000000,0,0.0,0.000,0.000,0.0,0.0,189037.800,94518.900000,94537.8,0.0,0.000000,0.0,0.000,0.00000,0.000,0.0,NaN,NaN,0,0,0,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0
100005,3,-373,-62,-190.666667,-128.0,1324.0,439.333333,-123.0,-123.0,-123.000000,-121,-11,-54.333333,0,0.0,0.000,0.000,0.0,0.0,657126.000,219042.000000,568800.0,568408.5,189469.500000,543087.0,0.000,0.00000,0.000,4261.5,1420.500000,4261.5,0,0,2,0,1,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
df=df.merge(bureau_agg, on="SK_ID_CURR", how="left")

In [ ]:
df.shape

(307511, 170)

In [1]:
def aggregate_file(df, group_by_col, categorical_overrides=None, cols_to_exclude=None ,id_col=None, prefix=None):
  numerical_features1 = set(df.select_dtypes(include=[np.number]).columns)
  categorical_features1 = set(df.select_dtypes(include=['object']).columns)
  categorical_overrides = set(categorical_overrides or [])
  cols_to_exclude = set(cols_to_exclude or [])
  categorical_features1 = categorical_features1.union(categorical_overrides)
  numerical_features1 = numerical_features1.difference(categorical_overrides)
  numerical_features1 = numerical_features1.difference(cols_to_exclude)
  categorical_features1 = categorical_features1.difference(cols_to_exclude)
  numerical_features1 = numerical_features1.difference({group_by_col})
  numerical_features1 = numerical_features1.difference({id_col})
  categorical_features1 = categorical_features1.difference({group_by_col})
  dummies = pd.DataFrame(index=df.index)
  if categorical_features1:
    dummies = pd.get_dummies(df[list(categorical_features1)], dtype=bool)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(columns=list(categorical_features1))
  aggregations = {}
  if id_col :
    aggregations[id_col] = ["count"]
  for col in sorted(numerical_features1):
    aggregations[col] = ["mean", "max", "sum","min"]

  for col in sorted(dummies.columns):
    aggregations[col] = ["sum"]
  agg_df = df.groupby(group_by_col).agg(aggregations)
  agg_df.columns = [f"{col}_{agg}" for col, agg in agg_df.columns]
  if prefix:
    agg_df.columns = [f"{prefix}_{col}" for col in agg_df.columns]
  return agg_df

In [ ]:
test_agg = aggregate_file(df_b, "SK_ID_CURR", id_col="SK_ID_BUREAU")
print(test_agg.shape)
print(bureau_agg.shape)

manual_cols = set(bureau_agg.columns)
auto_cols = set(test_agg.columns)
print("In manual but not in auto:")
print(manual_cols - auto_cols)

(305811, 53)
(305811, 52)
In manual but not in auto:
{'CREDIT_TYPE_Microloan_sum', 'CREDIT_ACTIVE_Sold_sum', 'CREDIT_TYPE_Consumer credit_sum', 'CREDIT_TYPE_Cash loan (non-earmarked)_sum', 'CREDIT_TYPE_Mobile operator loan_sum', 'CREDIT_TYPE_Car loan_sum', 'CREDIT_ACTIVE_Bad debt_sum', 'CREDIT_TYPE_Unknown type of loan_sum', 'CREDIT_TYPE_Credit card_sum', 'CREDIT_TYPE_Loan for the purchase of equipment_sum', 'CREDIT_ACTIVE_Active_sum', 'CREDIT_TYPE_Loan for business development_sum', 'CREDIT_TYPE_Loan for purchase of shares (margin lending)_sum', 'CREDIT_ACTIVE_Closed_sum', 'CREDIT_TYPE_Interbank credit_sum', 'CREDIT_TYPE_Another type of loan_sum', 'CREDIT_TYPE_Real estate loan_sum', 'CREDIT_TYPE_Loan for working capital replenishment_sum', 'CREDIT_TYPE_Mortgage_sum'}

In [ ]:
df_p = pd.read_csv("previous_application.csv")
print(df_p.shape)
print(df_p.dtypes)

(1670214, 37)
SK_ID_PREV                       int64
SK_ID_CURR                       int64
NAME_CONTRACT_TYPE              object
AMT_ANNUITY                    float64
AMT_APPLICATION                float64
AMT_CREDIT                     float64
AMT_DOWN_PAYMENT               float64
AMT_GOODS_PRICE                float64
WEEKDAY_APPR_PROCESS_START      object
HOUR_APPR_PROCESS_START          int64
FLAG_LAST_APPL_PER_CONTRACT     object
NFLAG_LAST_APPL_IN_DAY           int64
RATE_DOWN_PAYMENT              float64
RATE_INTEREST_PRIMARY          float64
RATE_INTEREST_PRIVILEGED       float64
NAME_CASH_LOAN_PURPOSE          object
NAME_CONTRACT_STATUS            object
DAYS_DECISION                    int64
NAME_PAYMENT_TYPE               object
CODE_REJECT_REASON              object
NAME_TYPE_SUITE                 object
NAME_CLIENT_TYPE                object
NAME_GOODS_CATEGORY             object
NAME_PORTFOLIO                  object
NAME_PRODUCT_TYPE               object
CHANNEL_TYPE                    object
SELLERPLACE_AREA                 int64
NAME_SELLER_INDUSTRY            object
CNT_PAYMENT                    float64
NAME_YIELD_GROUP                object
PRODUCT_COMBINATION             object
DAYS_FIRST_DRAWING             float64
DAYS_FIRST_DUE                 float64
DAYS_LAST_DUE_1ST_VERSION      float64
DAYS_LAST_DUE                  float64
DAYS_TERMINATION               float64
NFLAG_INSURED_ON_APPROVAL      float64
dtype: object

In [ ]:
print(df_p["DAYS_FIRST_DRAWING"].value_counts().head())
print(df_p["DAYS_FIRST_DUE"].value_counts().head())
print(df_p["DAYS_LAST_DUE_1ST_VERSION"].value_counts().head())
print(df_p["DAYS_LAST_DUE"].value_counts().head())
print(df_p["DAYS_TERMINATION"].value_counts().head())
tmp = ["DAYS_FIRST_DRAWING","DAYS_FIRST_DUE","DAYS_LAST_DUE_1ST_VERSION","DAYS_LAST_DUE","DAYS_TERMINATION"]

DAYS_FIRST_DRAWING
 365243.0    934444
-228.0          123
-212.0          121
-224.0          121
-223.0          119
Name: count, dtype: int64
DAYS_FIRST_DUE
 365243.0    40645
-334.0         772
-509.0         760
-208.0         751
-330.0         750
Name: count, dtype: int64
DAYS_LAST_DUE_1ST_VERSION
365243.0    93864
9.0           720
8.0           706
0.0           705
5.0           702
Name: count, dtype: int64
DAYS_LAST_DUE
 365243.0    211221
-245.0          658
-188.0          650
-239.0          642
-167.0          638
Name: count, dtype: int64
DAYS_TERMINATION
 365243.0    225913
-233.0          786
-184.0          770
-170.0          770
-163.0          769
Name: count, dtype: int64

In [ ]:
tmp = ["DAYS_FIRST_DRAWING","DAYS_FIRST_DUE","DAYS_LAST_DUE_1ST_VERSION","DAYS_LAST_DUE","DAYS_TERMINATION"]

df_p[tmp] = df_p[tmp].replace(365243, np.nan)

In [ ]:
df_p_tmp = aggregate_file(df=df_p, group_by_col="SK_ID_CURR", categorical_overrides=["NAME_CONTRACT_STATUS"], id_col="SK_ID_PREV", prefix="PREV")

In [ ]:
df_p_tmp.shape

(338857, 220)

In [ ]:
df = df=df.merge(df_p_tmp, on="SK_ID_CURR", how="left")

In [ ]:
df.shape

(307511, 390)

In [ ]:
df_cols = df.columns
df_cols

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'PREV_PRODUCT_COMBINATION_POS mobile without interest_sum',
       'PREV_PRODUCT_COMBINATION_POS other with interest_sum',
       'PREV_PRODUCT_COMBINATION_POS others without interest_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_sum',
       'PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_sum'],
      dtype='object', length=390)

In [ ]:
df_pcb = pd.read_csv("POS_CASH_balance.csv")
print(df_pcb.shape)
df_pcb_tmp = aggregate_file(df=df_pcb, group_by_col="SK_ID_CURR", categorical_overrides=["NAME_CONTRACT_STATUS"], id_col="SK_ID_PREV", prefix="POS")
print(df_pcb_tmp.shape)
print(df.shape)
df = df=df.merge(df_pcb_tmp, on="SK_ID_CURR", how="left")
print(df.shape)

(10001358, 8)
(337252, 30)
(307511, 390)
(307511, 420)

In [ ]:
df_ccb = pd.read_csv("credit_card_balance.csv")
print(df_ccb.shape)
df_ccb_tmp = aggregate_file(df=df_ccb, group_by_col="SK_ID_CURR", categorical_overrides=["NAME_CONTRACT_STATUS"], id_col="SK_ID_PREV", prefix="CC")
print(df_ccb_tmp.shape)
print(df.shape)
df = df=df.merge(df_ccb_tmp, on="SK_ID_CURR", how="left")
print(df.shape)

(3840312, 23)
(103558, 88)
(307511, 420)
(307511, 508)

In [ ]:
df_ip = pd.read_csv("installments_payments.csv")
print(df_ip.shape)
df_ip_tmp = aggregate_file(df=df_ip, group_by_col="SK_ID_CURR",id_col="SK_ID_PREV", prefix="INSTAL")
print(df_ip_tmp.shape)
print(df.shape)
df_ip_tmp = df_ip_tmp.rename(columns={"SK_ID_PREV_count": "INSTAL_SK_ID_PREV_count"})
df = df=df.merge(df_ip_tmp, on="SK_ID_CURR", how="left")
print(df.shape)

(13605401, 8)
(339587, 25)
(307511, 508)
(307511, 533)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
#import xgboost as xgb
#import catboost as cb
import re
import numpy as np
from sklearn.model_selection import StratifiedKFold
# import optuna
df = pd.read_parquet('checkpoint_final.parquet')

In [ ]:
cat_cols = df.select_dtypes(include='object').columns.tolist()

In [ ]:
df[cat_cols].nunique().sort_values(ascending=False)

ORGANIZATION_TYPE             58
OCCUPATION_TYPE               18
NAME_INCOME_TYPE               8
NAME_TYPE_SUITE                7
WALLSMATERIAL_MODE             7
WEEKDAY_APPR_PROCESS_START     7
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
NAME_EDUCATION_TYPE            5
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
CODE_GENDER                    3
FLAG_OWN_CAR                   2
NAME_CONTRACT_TYPE             2
FLAG_OWN_REALTY                2
EMERGENCYSTATE_MODE            2
dtype: int64

In [ ]:
df[cat_cols] = df[cat_cols].apply(lambda x: x.astype('category').cat.codes)

In [ ]:
df[cat_cols].dtypes

NAME_CONTRACT_TYPE            int8
CODE_GENDER                   int8
FLAG_OWN_CAR                  int8
FLAG_OWN_REALTY               int8
NAME_TYPE_SUITE               int8
NAME_INCOME_TYPE              int8
NAME_EDUCATION_TYPE           int8
NAME_FAMILY_STATUS            int8
NAME_HOUSING_TYPE             int8
OCCUPATION_TYPE               int8
WEEKDAY_APPR_PROCESS_START    int8
ORGANIZATION_TYPE             int8
FONDKAPREMONT_MODE            int8
HOUSETYPE_MODE                int8
WALLSMATERIAL_MODE            int8
EMERGENCYSTATE_MODE           int8
dtype: object

In [ ]:
exclude = ["SK_ID_CURR", "TARGET"]
X = df.drop(columns=exclude)
y = df["TARGET"]

In [ ]:
print(X.shape)
print(y.shape)
print(y.value_counts())

(307511, 531)
(307511,)
TARGET
0    282686
1     24825
Name: count, dtype: int64

In [ ]:
X.columns = [re.sub(r'[^A-Za-z0-9_]', '_', col) for col in X.columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y)

In [ ]:
# lightgbm_model = lgb.LGBMClassifier(n_estimators=500,
#                                     learning_rate=0.05,
#                                     num_leaves=31,
#                                     random_state=42,
#                                     n_jobs=-1)
# xgboost_model = xgb.XGBClassifier(n_estimators=500,
#                                     learning_rate=0.05,
#                                     max_depth=6,
#                                     random_state=42,
#                                     n_jobs=-1)
# catboost_model = cb.CatBoostClassifier(n_estimators=500,
#                                     learning_rate=0.05,
#                                     depth=6,
#                                     random_state=42)

# lightgbm_model.fit(X_train, y_train)
# xgboost_model.fit(X_train, y_train)
# catboost_model.fit(X_train, y_train)

# y_pred_proba_lightgbm = lightgbm_model.predict_proba(X_test)[:, 1]
# y_pred_proba_xgboost = xgboost_model.predict_proba(X_test)[:, 1]
# y_pred_proba_catboost = catboost_model.predict_proba(X_test)[:, 1]


# auc_lightgbm = roc_auc_score(y_test, y_pred_proba_lightgbm)
# auc_xgboost = roc_auc_score(y_test, y_pred_proba_xgboost)
# auc_catboost = roc_auc_score(y_test, y_pred_proba_catboost)

# print("LightGBM AUC:", auc_lightgbm)
# print("XGBoost AUC:", auc_xgboost)
# print("CatBoost AUC:", auc_catboost)

In [ ]:
# import joblib
# joblib.dump(lightgbm_model, 'lgbm_baseline.pkl')
# joblib.dump(xgboost_model, 'xgb_baseline.pkl')
# joblib.dump(catboost_model, 'catboost_baseline.pkl')

In [ ]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
aucs = []
for train_idx, val_idx in skf.split(X, y):

    X_train_fold = X.iloc[train_idx]
    X_val_fold   = X.iloc[val_idx]

    y_train_fold = y.iloc[train_idx]
    y_val_fold   = y.iloc[val_idx]
    model = lgb.LGBMClassifier(n_estimators=500,
                                    learning_rate=0.05,
                                    num_leaves=31,
                                    random_state=42,
                                     n_jobs=-1,
                               scale_pos_weight=11.38
                               , device="gpu")
    model.fit(X_train_fold, y_train_fold)

    y_pred = model.predict_proba(X_val_fold)[:, 1]
    auc = roc_auc_score(y_val_fold, y_pred)
    aucs.append(auc)
    print(f"Fold AUC: {auc}")
print(f"The average AUC is {np.mean(aucs)} | and the standard deviation is {np.std(aucs)}")

[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62851
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 530
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 279 dense feature groups (65.69 MB) transferred to GPU in 0.078281 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
Fold AUC: 0.7815063860836033
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62964
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 530
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 279 dense feature groups (65.69 MB) transferred to GPU in 0.076544 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Fold AUC: 0.7885995323829768
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62896
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 530
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 279 dense feature groups (65.69 MB) transferred to GPU in 0.080458 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Fold AUC: 0.7794423318857523
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62867
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 530
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 279 dense feature groups (65.69 MB) transferred to GPU in 0.076711 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Fold AUC: 0.7862061581431732
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62864
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 530
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 279 dense feature groups (65.69 MB) transferred to GPU in 0.079451 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Fold AUC: 0.7796678096232322
The average AUC is 0.7830844436237475 | and the standard deviation is 0.003676681573606701

In [ ]:
importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

In [ ]:
(importance_df["importance"] == 0).sum()

np.int64(88)

In [ ]:
importance_df.sort_values(by="importance", ascending=False).head(10)

                    feature  importance
110         EXT_SOURCE_MEAN         296
15               DAYS_BIRTH         271
41             EXT_SOURCE_3         263
7               AMT_ANNUITY         258
16            DAYS_EMPLOYED         257
6                AMT_CREDIT         250
39             EXT_SOURCE_1         229
40             EXT_SOURCE_2         208
118         DAYS_CREDIT_max         187
514  INSTAL_AMT_PAYMENT_min         185

In [ ]:
zero_importance = importance_df[importance_df['importance'] == 0]['feature'].tolist()
X_filtered = X.drop(columns=zero_importance)
print(X_filtered.shape)

(307511, 443)

In [ ]:
X_filtered.to_parquet("X_filtered_checkpoint.parquet")
y.to_csv("y_checkpoint.csv", index=False)

In [ ]:
# from sklearn.model_selection import StratifiedKFold
# skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# aucs = []
# for train_idx, val_idx in skf.split(X_filtered, y):

#     X_train_fold = X_filtered.iloc[train_idx]
#     X_val_fold   = X_filtered.iloc[val_idx]

#     y_train_fold = y.iloc[train_idx]
#     y_val_fold   = y.iloc[val_idx]
#     model = lgb.LGBMClassifier(n_estimators=500,
#                                     learning_rate=0.05,
#                                     num_leaves=31,
#                                     random_state=42,
#                                      n_jobs=-1,
#                                scale_pos_weight=11.38,
#                                device="gpu")
#     model.fit(X_train_fold, y_train_fold)

#     y_pred = model.predict_proba(X_val_fold)[:, 1]
#     auc = roc_auc_score(y_val_fold, y_pred)
#     aucs.append(auc)
#     print(f"Fold AUC: {auc}")
# print(f"The average AUC is {np.mean(aucs)} | and the standard deviation is {np.std(aucs)}")

In [ ]:
def objective(trial):

    params = {
        "num_leaves": trial.suggest_int("num_leaves", 20, 150),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 200),
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "random_state": 42,
        "n_jobs": -1,
        "device": "gpu" ,
        "scale_pos_weight": 11.38
    }

    model = lgb.LGBMClassifier(**params)

    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

    aucs = []

    for train_idx, val_idx in skf.split(X_filtered, y):

        X_train_fold = X_filtered.iloc[train_idx]
        X_val_fold   = X_filtered.iloc[val_idx]

        y_train_fold = y.iloc[train_idx]
        y_val_fold   = y.iloc[val_idx]

        model.fit(X_train_fold, y_train_fold)

        y_pred = model.predict_proba(X_val_fold)[:, 1]

        auc = roc_auc_score(y_val_fold, y_pred)

        aucs.append(auc)

    return np.mean(aucs)
# optuna.logging.set_verbosity(optuna.logging.WARNING)
# study = optuna.create_study(direction="maximize")
# study.optimize(objective, n_trials=50)

Streaming output truncated to the last 5000 lines.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 16550, number of negative: 188457
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 62093
[LightGBM] [Info] Number of data points in the train set: 205007, number of used features: 445
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 275 dense feature groups (53.96 MB) transferred to GPU in 0.069236 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432484
[LightGBM] [Info] Start training from score -2.432484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [ ]:
print("Best AUC:", study.best_value)
print("Best params:", study.best_params)

Best AUC: 0.7838971254803239
Best params: {'num_leaves': 24, 'learning_rate': 0.048305996356334056, 'max_depth': 4, 'min_child_samples': 200, 'n_estimators': 823}

In [ ]:
!pip install -q fastparquet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 4.8 MB/s eta 0:00:00

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
#import xgboost as xgb
#import catboost as cb
import re
import numpy as np
from sklearn.model_selection import StratifiedKFold
# import optuna
df = pd.read_parquet('X_filtered_checkpoint.parquet')
tar = pd.read_csv("y_checkpoint.csv")

In [3]:
df["credit_to_goods_price"] = df["AMT_CREDIT"] / df["AMT_GOODS_PRICE"]
df["loan_to_income"] = df["AMT_CREDIT"] / df["AMT_INCOME_TOTAL"]
df["annuity_to_income"] = df["AMT_ANNUITY"] / df["AMT_INCOME_TOTAL"]

In [4]:
df["TARGET"] = tar

In [5]:
df["annuity_income_bin"] = pd.qcut(df["annuity_to_income"], 4)
df["credit_to_goods_price_bin"] = pd.qcut(df["credit_to_goods_price"], 4)
df["loan_to_income_bin"] = pd.qcut(df["loan_to_income"], 4)
print(df.groupby("annuity_income_bin")["TARGET"].mean())
print(df.groupby("credit_to_goods_price_bin")["TARGET"].mean())
print(df.groupby("loan_to_income_bin")["TARGET"].mean())

annuity_income_bin
(-0.000776, 0.115]    0.072923
(0.115, 0.163]        0.078816
(0.163, 0.229]        0.085374
(0.229, 1.876]        0.085817
Name: TARGET, dtype: float64
credit_to_goods_price_bin
(0.149, 1.0]      0.067466
(1.0, 1.119]      0.062112
(1.119, 1.198]    0.081361
(1.198, 6.0]      0.117144
Name: TARGET, dtype: float64
loan_to_income_bin
(0.00381, 2.019]    0.074622
(2.019, 3.265]      0.087219
(3.265, 5.16]       0.087436
(5.16, 84.737]      0.073650
Name: TARGET, dtype: float64

/tmp/ipykernel_94715/3742423296.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby("annuity_income_bin")["TARGET"].mean())
/tmp/ipykernel_94715/3742423296.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby("credit_to_goods_price_bin")["TARGET"].mean())
/tmp/ipykernel_94715/3742423296.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby("loan_to_income_bin")["TARGET"].mean())

In [6]:
X_filtered = df.drop(columns=[
    "TARGET",
    "annuity_income_bin",
    "credit_to_goods_price_bin",
    "loan_to_income_bin"
])
y = df["TARGET"]

In [7]:
print(df.shape)
print([col for col in df.columns if col in ['credit_to_goods_price', 'loan_to_income', 'annuity_to_income']])

(307511, 450)
['credit_to_goods_price', 'loan_to_income', 'annuity_to_income']

In [8]:
X_filtered["age"] = -X_filtered["DAYS_BIRTH"]

X_filtered["ext_mean_x_age"] = (
    X_filtered["EXT_SOURCE_MEAN"] * X_filtered["age"]
)

X_filtered["ext_mean_x_annuity_income"] = (
    X_filtered["EXT_SOURCE_MEAN"] * X_filtered["annuity_to_income"]
)

X_filtered["ext_mean_x_loan_income"] = (
    X_filtered["EXT_SOURCE_MEAN"] * X_filtered["loan_to_income"]
)

X_filtered["ext_mean_x_employment"] = (
    X_filtered["EXT_SOURCE_MEAN"] * X_filtered["DAYS_EMPLOYED"]
)

In [9]:
# skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
# aucs = []
# for train_idx, val_idx in skf.split(X_filtered, y):

#     X_train_fold = X_filtered.iloc[train_idx]
#     X_val_fold   = X_filtered.iloc[val_idx]

#     y_train_fold = y.iloc[train_idx]
#     y_val_fold   = y.iloc[val_idx]
#     model = lgb.LGBMClassifier(n_estimators=823,
#                                     learning_rate=0.048305996356334056,
#                                     num_leaves=24,
#                                     max_depth=4,
#                                     min_child_samples=200,
#                                     random_state=42,
#                                      n_jobs=-1,
#                                scale_pos_weight=11.38)
#     model.fit(X_train_fold, y_train_fold)

#     y_pred = model.predict_proba(X_val_fold)[:, 1]
#     auc = roc_auc_score(y_val_fold, y_pred)
#     aucs.append(auc)
#     print(f"Fold AUC: {auc}")
# print(f"The average AUC is {np.mean(aucs)} | and the standard deviation is {np.std(aucs)}")

In [10]:
df_bb = pd.read_csv("bureau_balance.csv")
print(df_bb.shape)
df_bb.head(10)

(27299925, 3)

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C
5       5715448              -5      C
6       5715448              -6      C
7       5715448              -7      C
8       5715448              -8      C
9       5715448              -9      0

In [11]:
df_bb['STATUS'].value_counts()

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [12]:
df_bb['STATUS_numeric'] = df_bb['STATUS'].map({'C': 0, 'X': 0, '0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5})
df_bb['has_bad_payment'] = (df_bb['STATUS_numeric'] >= 1).astype(int)

In [13]:
print(df_bb[['STATUS', 'STATUS_numeric', 'has_bad_payment']].head())

  STATUS  STATUS_numeric  has_bad_payment
0      C               0                0
1      C               0                0
2      C               0                0
3      C               0                0
4      C               0                0

In [14]:
bb_agg = aggregate_file(
    df_bb,
    group_by_col="SK_ID_BUREAU",
    cols_to_exclude=["STATUS"],
    prefix="BB"
)

In [15]:
bb_agg.shape

(817395, 12)

In [16]:
df_b = pd.read_csv("bureau.csv")
df_b.columns
bureau_merged = df_b.merge(bb_agg, on="SK_ID_BUREAU", how="left")

In [17]:
bureau_merged.shape

(1716428, 29)

In [18]:
bureau_curr_agg = aggregate_file(
    bureau_merged,
    group_by_col="SK_ID_CURR",
    id_col="SK_ID_BUREAU",
    prefix="BUREAU"
)
bureau_curr_agg.shape

(305811, 120)

In [19]:
X_filtered.head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,INSTAL_NUM_INSTALMENT_VERSION_sum,INSTAL_NUM_INSTALMENT_VERSION_min,credit_to_goods_price,loan_to_income,annuity_to_income,age,ext_mean_x_age,ext_mean_x_annuity_income,ext_mean_x_loan_income,ext_mean_x_employment
0,0,1,0,1,0,202500.0,406597.5,24700.5,351000.0,6,...,20.0,1.0,1.158397,2.007889,0.121978,9461,1530.667880,0.019734,0.324851,-103.058391
1,0,0,0,0,0,270000.0,1293502.5,35698.5,1129500.0,1,...,26.0,1.0,1.145199,4.790750,0.132217,16765,7825.173449,0.061713,2.236114,-554.506773
2,1,1,1,1,0,67500.0,135000.0,6750.0,135000.0,6,...,4.0,1.0,1.000000,2.000000,0.100000,19046,12241.614366,0.064274,1.285479,-144.616362
3,0,0,0,1,0,135000.0,312682.5,29686.5,297000.0,6,...,18.0,1.0,1.052803,2.316167,0.219900,19005,12361.644326,0.143032,1.506531,-1976.692297
4,0,1,0,1,0,121500.0,513000.0,21865.5,513000.0,6,...,77.0,1.0,1.000000,4.222222,0.179963,19932,6432.819536,0.058081,1.362673,-980.478916

In [20]:
full_df = pd.read_parquet("checkpoint_final.parquet")

In [21]:
X_filtered["SK_ID_CURR"] = full_df["SK_ID_CURR"].values
X_filtered = X_filtered.merge(bureau_curr_agg, on="SK_ID_CURR", how="left")
X_filtered = X_filtered.drop(columns=["SK_ID_CURR"])

In [22]:
X_filtered.shape

(307511, 571)

In [23]:
del full_df, df_b, df_bb, bb_agg, bureau_merged, bureau_curr_agg
import gc
gc.collect()

90

In [24]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
aucs = []
for train_idx, val_idx in skf.split(X_filtered, y):

    X_train_fold = X_filtered.iloc[train_idx]
    X_val_fold   = X_filtered.iloc[val_idx]

    y_train_fold = y.iloc[train_idx]
    y_val_fold   = y.iloc[val_idx]
    model = lgb.LGBMClassifier(n_estimators=823,
                                    learning_rate=0.048305996356334056,
                                    num_leaves=24,
                                    max_depth=4,
                                    min_child_samples=200,
                                    random_state=42,
                                     n_jobs=-1,
                               scale_pos_weight=11.38)
    model.fit(X_train_fold, y_train_fold)

    y_pred = model.predict_proba(X_val_fold)[:, 1]
    auc = roc_auc_score(y_val_fold, y_pred)
    aucs.append(auc)
    print(f"Fold AUC: {auc}")
print(f"The average AUC is {np.mean(aucs)} | and the standard deviation is {np.std(aucs)}")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16550, number of negative: 188457
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 4.419394 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 82138
[LightGBM] [Info] Number of data points in the train set: 205007, number of used features: 571
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432484
[LightGBM] [Info] Start training from score -2.432484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf